### ISSUE TITLE
App become heavier and occacionally crash

### ISSUE THREAD

**Issue by haikalwikwik** [duyphuong5126/H-Manga#4]
After update loading manga feels so slow and occasionally the app crash. Using android v 6.0

**Comment by duyphuong5126** [comment]
> After update loading manga feels so slow and occasionally the app crash. Using android v 6.0

Thank you for your feedback. I'm sorry for replying to you this late.

I'm monitoring the reports of crashes and user's experience and going to fix all of them. There will be a new version soon.

If you feel better with the old versions, please downgrade the app. I always hope my users stay up to date, but their experiences are also the top priority. Please stay where you feel comfortable; I will make the next version better for you.

Thank you. Have a nice day.
